<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ActividadEconomicaSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::table('actividades_economicas')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1');

        $actividades = $this->getCodes();

        // Insertar en lotes de 100 para rendimiento
        foreach (array_chunk($actividades, 100) as $lote) {
            DB::table('actividades_economicas')->insert($lote);
        }
    }

    private function getCodes(): array
    {
        $now = now()->toDateTimeString();

        $makeRow = function (string $codigo, string $seccion, string $nombreSeccion, string $nombre) use ($now): array {
            return [
                'codigo'         => $codigo,
                'seccion'        => $seccion,
                'nombre_seccion' => $nombreSeccion,
                'nombre'         => $nombre,
                'activo'         => true,
                'created_at'     => $now,
                'updated_at'     => $now,
            ];
        };

        return [
            // =========================================================
            // SECCIÓN A: Agricultura, ganadería, caza, silvicultura y pesca
            // =========================================================
            $makeRow('0111', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Cultivo de cereales (excepto arroz), legumbres y semillas oleaginosas'),
            $makeRow('0112', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Cultivo de arroz'),
            $makeRow('0113', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Cultivo de hortalizas, raíces y tubérculos'),
            $makeRow('0114', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Cultivo de caña de azúcar'),
            $makeRow('0115', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Cultivo de tabaco'),
            $makeRow('0116', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Cultivo de plantas de fibras'),
            $makeRow('0119', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Otros cultivos transitorios'),
            $makeRow('0121', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Cultivo de frutas tropicales y subtropicales'),
            $makeRow('0122', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Cultivo de plátano y banano'),
            $makeRow('0123', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Cultivo de café'),
            $makeRow('0124', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Cultivo de caña panelera'),
            $makeRow('0125', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Cultivo de flor de corte'),
            $makeRow('0126', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Cultivo de palma para aceite (palma africana) y otros frutos oleaginosos'),
            $makeRow('0127', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Cultivo de plantas con las que se preparan bebidas'),
            $makeRow('0128', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Cultivo de especias y de plantas aromáticas y medicinales'),
            $makeRow('0129', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Otros cultivos permanentes'),
            $makeRow('0130', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Propagación de plantas (viveros, excepto viveros forestales)'),
            $makeRow('0141', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Cría de ganado bovino y bufalino'),
            $makeRow('0142', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Cría de caballos y otros equinos'),
            $makeRow('0143', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Cría de ovejas y cabras'),
            $makeRow('0144', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Cría de ganado porcino'),
            $makeRow('0145', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Cría de aves de corral'),
            $makeRow('0149', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Cría de otros animales'),
            $makeRow('0150', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Explotación mixta (agrícola y pecuaria)'),
            $makeRow('0161', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Actividades de apoyo a la agricultura'),
            $makeRow('0162', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Actividades de apoyo a la ganadería'),
            $makeRow('0163', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Actividades poscosecha'),
            $makeRow('0164', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Tratamiento de semillas para propagación'),
            $makeRow('0170', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Caza ordinaria y mediante trampas, y actividades de servicios conexas'),
            $makeRow('0210', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Silvicultura y otras actividades forestales'),
            $makeRow('0220', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Extracción de madera'),
            $makeRow('0230', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Recolección de productos forestales diferentes a la madera'),
            $makeRow('0240', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Actividades de apoyo a la silvicultura'),
            $makeRow('0311', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Pesca marítima'),
            $makeRow('0312', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Pesca de agua dulce'),
            $makeRow('0321', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Acuicultura marítima'),
            $makeRow('0322', 'A', 'Agricultura, ganadería, caza, silvicultura y pesca', 'Acuicultura de agua dulce'),

            // =========================================================
            // SECCIÓN B: Explotación de minas y canteras
            // =========================================================
            $makeRow('0510', 'B', 'Explotación de minas y canteras', 'Extracción de hulla (carbón de piedra)'),
            $makeRow('0520', 'B', 'Explotación de minas y canteras', 'Extracción de carbón lignito'),
            $makeRow('0610', 'B', 'Explotación de minas y canteras', 'Extracción de petróleo crudo'),
            $makeRow('0620', 'B', 'Explotación de minas y canteras', 'Extracción de gas natural'),
            $makeRow('0710', 'B', 'Explotación de minas y canteras', 'Extracción de minerales de hierro'),
            $makeRow('0721', 'B', 'Explotación de minas y canteras', 'Extracción de minerales de uranio y torio'),
            $makeRow('0722', 'B', 'Explotación de minas y canteras', 'Extracción de oro y otros metales preciosos'),
            $makeRow('0723', 'B', 'Explotación de minas y canteras', 'Extracción de minerales de níquel'),
            $makeRow('0729', 'B', 'Explotación de minas y canteras', 'Extracción de otros minerales metalíferos no ferrosos'),
            $makeRow('0810', 'B', 'Explotación de minas y canteras', 'Extracción de piedra, arena, arcillas, caliza, yeso, sal y similares'),
            $makeRow('0820', 'B', 'Explotación de minas y canteras', 'Extracción de esmeraldas, piedras preciosas y semipreciosas'),
            $makeRow('0891', 'B', 'Explotación de minas y canteras', 'Extracción de minerales para la fabricación de abonos y productos químicos'),
            $makeRow('0892', 'B', 'Explotación de minas y canteras', 'Extracción de turba'),
            $makeRow('0893', 'B', 'Explotación de minas y canteras', 'Extracción de sal'),
            $makeRow('0899', 'B', 'Explotación de minas y canteras', 'Extracción de otros minerales no metálicos no clasificados en otra parte'),
            $makeRow('0910', 'B', 'Explotación de minas y canteras', 'Actividades de apoyo para la extracción de petróleo y de gas natural'),
            $makeRow('0990', 'B', 'Explotación de minas y canteras', 'Actividades de apoyo para otras actividades de explotación de minas y canteras'),

            // =========================================================
            // SECCIÓN C: Industrias manufactureras
            // =========================================================
            $makeRow('1011', 'C', 'Industrias manufactureras', 'Procesamiento y conservación de carne y productos cárnicos'),
            $makeRow('1012', 'C', 'Industrias manufactureras', 'Procesamiento y conservación de pescados, crustáceos y moluscos'),
            $makeRow('1013', 'C', 'Industrias manufactureras', 'Procesamiento y conservación de frutas, legumbres, hortalizas y tubérculos'),
            $makeRow('1020', 'C', 'Industrias manufactureras', 'Elaboración de aceites y grasas de origen vegetal y animal'),
            $makeRow('1030', 'C', 'Industrias manufactureras', 'Elaboración de productos lácteos'),
            $makeRow('1040', 'C', 'Industrias manufactureras', 'Elaboración de productos de molinería, almidones y productos derivados del almidón'),
            $makeRow('1051', 'C', 'Industrias manufactureras', 'Elaboración de productos de panadería'),
            $makeRow('1052', 'C', 'Industrias manufactureras', 'Elaboración de macarrones, fideos, alcuzcuz y productos farináceos similares'),
            $makeRow('1061', 'C', 'Industrias manufactureras', 'Trilla de café'),
            $makeRow('1062', 'C', 'Industrias manufactureras', 'Descafeinado, tostión y molienda del café'),
            $makeRow('1063', 'C', 'Industrias manufactureras', 'Otros derivados del café'),
            $makeRow('1071', 'C', 'Industrias manufactureras', 'Elaboración y refinación de azúcar'),
            $makeRow('1072', 'C', 'Industrias manufactureras', 'Elaboración de panela'),
            $makeRow('1081', 'C', 'Industrias manufactureras', 'Elaboración de cacao, chocolate y productos de confitería'),
            $makeRow('1082', 'C', 'Industrias manufactureras', 'Elaboración de otros productos alimenticios no clasificados en otra parte'),
            $makeRow('1083', 'C', 'Industrias manufactureras', 'Elaboración de comidas y platos preparados'),
            $makeRow('1101', 'C', 'Industrias manufactureras', 'Destilación, rectificación y mezcla de bebidas alcohólicas'),
            $makeRow('1102', 'C', 'Industrias manufactureras', 'Elaboración de bebidas fermentadas no destiladas'),
            $makeRow('1103', 'C', 'Industrias manufactureras', 'Producción de malta, elaboración de cervezas y otras bebidas malteadas'),
            $makeRow('1104', 'C', 'Industrias manufactureras', 'Elaboración de bebidas no alcohólicas; producción de aguas minerales y otras aguas embotelladas'),
            $makeRow('1200', 'C', 'Industrias manufactureras', 'Elaboración de productos de tabaco'),
            $makeRow('1311', 'C', 'Industrias manufactureras', 'Preparación e hilatura de fibras textiles'),
            $makeRow('1312', 'C', 'Industrias manufactureras', 'Tejeduría de productos textiles'),
            $makeRow('1313', 'C', 'Industrias manufactureras', 'Acabado de productos textiles'),
            $makeRow('1391', 'C', 'Industrias manufactureras', 'Fabricación de tejidos de punto y ganchillo'),
            $makeRow('1392', 'C', 'Industrias manufactureras', 'Confección de artículos con materiales textiles, excepto prendas de vestir'),
            $makeRow('1393', 'C', 'Industrias manufactureras', 'Fabricación de tapetes y alfombras para pisos'),
            $makeRow('1394', 'C', 'Industrias manufactureras', 'Fabricación de cuerdas, cordeles, cables, bramantes y redes'),
            $makeRow('1399', 'C', 'Industrias manufactureras', 'Fabricación de otros productos textiles no clasificados en otra parte'),
            $makeRow('1410', 'C', 'Industrias manufactureras', 'Confección de prendas de vestir, excepto prendas de piel'),
            $makeRow('1420', 'C', 'Industrias manufactureras', 'Fabricación de artículos de piel'),
            $makeRow('1430', 'C', 'Industrias manufactureras', 'Fabricación de artículos de punto y ganchillo'),
            $makeRow('1511', 'C', 'Industrias manufactureras', 'Curtido y recurtido de cueros; recurtido y teñido de pieles'),
            $makeRow('1512', 'C', 'Industrias manufactureras', 'Fabricación de artículos de viaje, bolsos de mano y artículos de talabartería y guarnicionería'),
            $makeRow('1521', 'C', 'Industrias manufactureras', 'Fabricación de calzado de cuero y piel, con cualquier tipo de suela'),
            $makeRow('1522', 'C', 'Industrias manufactureras', 'Fabricación de otros tipos de calzado, excepto el calzado de cuero y piel'),
            $makeRow('1610', 'C', 'Industrias manufactureras', 'Aserrado, acepillado e impregnación de la madera'),
            $makeRow('1620', 'C', 'Industrias manufactureras', 'Fabricación de hojas de madera para enchapado; tableros contrachapados, laminados y de partículas'),
            $makeRow('1630', 'C', 'Industrias manufactureras', 'Fabricación de partes y piezas de madera, carpintería y ebanistería para la construcción'),
            $makeRow('1640', 'C', 'Industrias manufactureras', 'Fabricación de recipientes de madera'),
            $makeRow('1690', 'C', 'Industrias manufactureras', 'Fabricación de otros productos de madera; artículos de corcho, cestería y espartería'),
            $makeRow('1701', 'C', 'Industrias manufactureras', 'Fabricación de pulpa (pasta) celulósica; fabricación de papel y cartón'),
            $makeRow('1702', 'C', 'Industrias manufactureras', 'Fabricación de papel y cartón ondulado; envases, empaques y embalajes de papel y cartón'),
            $makeRow('1709', 'C', 'Industrias manufactureras', 'Fabricación de otros artículos de papel y cartón'),
            $makeRow('1811', 'C', 'Industrias manufactureras', 'Actividades de impresión'),
            $makeRow('1812', 'C', 'Industrias manufactureras', 'Actividades de producción de copias a partir de grabaciones originales'),
            $makeRow('1820', 'C', 'Industrias manufactureras', 'Reproducción de grabaciones'),
            $makeRow('1910', 'C', 'Industrias manufactureras', 'Fabricación de productos de hornos de coque'),
            $makeRow('1921', 'C', 'Industrias manufactureras', 'Fabricación de productos de la refinación del petróleo'),
            $makeRow('1922', 'C', 'Industrias manufactureras', 'Actividad de mezcla de combustibles'),
            $makeRow('2011', 'C', 'Industrias manufactureras', 'Fabricación de sustancias y productos químicos básicos'),
            $makeRow('2012', 'C', 'Industrias manufactureras', 'Fabricación de abonos y compuestos inorgánicos nitrogenados'),
            $makeRow('2013', 'C', 'Industrias manufactureras', 'Fabricación de plásticos en formas primarias'),
            $makeRow('2014', 'C', 'Industrias manufactureras', 'Fabricación de caucho sintético en formas primarias'),
            $makeRow('2021', 'C', 'Industrias manufactureras', 'Fabricación de plaguicidas y otros productos químicos de uso agropecuario'),
            $makeRow('2022', 'C', 'Industrias manufactureras', 'Fabricación de pinturas, barnices y revestimientos similares, tintas para impresión y masillas'),
            $makeRow('2023', 'C', 'Industrias manufactureras', 'Fabricación de jabones, detergentes, perfumes y preparados de tocador'),
            $makeRow('2029', 'C', 'Industrias manufactureras', 'Fabricación de otros productos químicos no clasificados en otra parte'),
            $makeRow('2030', 'C', 'Industrias manufactureras', 'Fabricación de fibras sintéticas y artificiales'),
            $makeRow('2100', 'C', 'Industrias manufactureras', 'Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos'),
            $makeRow('2211', 'C', 'Industrias manufactureras', 'Fabricación de llantas y neumáticos de caucho'),
            $makeRow('2212', 'C', 'Industrias manufactureras', 'Reencauche de llantas usadas'),
            $makeRow('2219', 'C', 'Industrias manufactureras', 'Fabricación de otros productos de caucho'),
            $makeRow('2221', 'C', 'Industrias manufactureras', 'Fabricación de formas básicas de plástico'),
            $makeRow('2229', 'C', 'Industrias manufactureras', 'Fabricación de artículos de plástico no clasificados en otra parte'),
            $makeRow('2310', 'C', 'Industrias manufactureras', 'Fabricación de vidrio y productos de vidrio'),
            $makeRow('2391', 'C', 'Industrias manufactureras', 'Fabricación de productos refractarios'),
            $makeRow('2392', 'C', 'Industrias manufactureras', 'Fabricación de materiales de arcilla para la construcción'),
            $makeRow('2393', 'C', 'Industrias manufactureras', 'Fabricación de otros productos de cerámica y porcelana'),
            $makeRow('2394', 'C', 'Industrias manufactureras', 'Fabricación de cemento, cal y yeso'),
            $makeRow('2395', 'C', 'Industrias manufactureras', 'Fabricación de artículos de hormigón, cemento y yeso'),
            $makeRow('2396', 'C', 'Industrias manufactureras', 'Corte, tallado y acabado de la piedra'),
            $makeRow('2399', 'C', 'Industrias manufactureras', 'Fabricación de otros productos minerales no metálicos no clasificados en otra parte'),
            $makeRow('2410', 'C', 'Industrias manufactureras', 'Industrias básicas de hierro y de acero'),
            $makeRow('2421', 'C', 'Industrias manufactureras', 'Industrias básicas de metales preciosos'),
            $makeRow('2422', 'C', 'Industrias manufactureras', 'Industrias básicas de aluminio'),
            $makeRow('2429', 'C', 'Industrias manufactureras', 'Industrias básicas de otros metales no ferrosos'),
            $makeRow('2431', 'C', 'Industrias manufactureras', 'Fundición de hierro y acero'),
            $makeRow('2432', 'C', 'Industrias manufactureras', 'Fundición de metales no ferrosos'),
            $makeRow('2511', 'C', 'Industrias manufactureras', 'Fabricación de productos metálicos para uso estructural'),
            $makeRow('2512', 'C', 'Industrias manufactureras', 'Fabricación de tanques, depósitos y recipientes de metal'),
            $makeRow('2513', 'C', 'Industrias manufactureras', 'Fabricación de generadores de vapor'),
            $makeRow('2520', 'C', 'Industrias manufactureras', 'Fabricación de armas y municiones'),
            $makeRow('2591', 'C', 'Industrias manufactureras', 'Forja, prensado, estampado y laminado de metal; pulvimetalurgia'),
            $makeRow('2592', 'C', 'Industrias manufactureras', 'Tratamiento y revestimiento de metales; mecanizado'),
            $makeRow('2593', 'C', 'Industrias manufactureras', 'Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería'),
            $makeRow('2599', 'C', 'Industrias manufactureras', 'Fabricación de otros productos elaborados de metal no clasificados en otra parte'),
            $makeRow('2610', 'C', 'Industrias manufactureras', 'Fabricación de componentes y tableros electrónicos'),
            $makeRow('2620', 'C', 'Industrias manufactureras', 'Fabricación de computadoras y de equipo periférico'),
            $makeRow('2630', 'C', 'Industrias manufactureras', 'Fabricación de equipos de comunicaciones'),
            $makeRow('2640', 'C', 'Industrias manufactureras', 'Fabricación de aparatos electrónicos de consumo'),
            $makeRow('2651', 'C', 'Industrias manufactureras', 'Fabricación de equipo de medición, prueba, navegación y control'),
            $makeRow('2652', 'C', 'Industrias manufactureras', 'Fabricación de relojes'),
            $makeRow('2660', 'C', 'Industrias manufactureras', 'Fabricación de equipos de irradiación y equipo electrónico de uso médico y terapéutico'),
            $makeRow('2670', 'C', 'Industrias manufactureras', 'Fabricación de instrumentos ópticos y equipo fotográfico'),
            $makeRow('2680', 'C', 'Industrias manufactureras', 'Fabricación de soportes magnéticos y ópticos'),
            $makeRow('2711', 'C', 'Industrias manufactureras', 'Fabricación de motores, generadores, transformadores eléctricos y aparatos de distribución de energía'),
            $makeRow('2712', 'C', 'Industrias manufactureras', 'Fabricación de baterías y acumuladores eléctricos'),
            $makeRow('2720', 'C', 'Industrias manufactureras', 'Fabricación de hilos y cables eléctricos y de fibra óptica'),
            $makeRow('2730', 'C', 'Industrias manufactureras', 'Fabricación de dispositivos de cableado'),
            $makeRow('2740', 'C', 'Industrias manufactureras', 'Fabricación de equipos eléctricos de iluminación'),
            $makeRow('2750', 'C', 'Industrias manufactureras', 'Fabricación de aparatos de uso doméstico'),
            $makeRow('2790', 'C', 'Industrias manufactureras', 'Fabricación de otros tipos de aparatos y equipo eléctrico'),
            $makeRow('2811', 'C', 'Industrias manufactureras', 'Fabricación de motores, turbinas, y partes para motores de combustión interna'),
            $makeRow('2812', 'C', 'Industrias manufactureras', 'Fabricación de equipo de potencia hidráulica y neumática'),
            $makeRow('2813', 'C', 'Industrias manufactureras', 'Fabricación de otras bombas, compresores, grifos y válvulas'),
            $makeRow('2814', 'C', 'Industrias manufactureras', 'Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión'),
            $makeRow('2815', 'C', 'Industrias manufactureras', 'Fabricación de hornos, hogueras y quemadores para la alimentación de hogares'),
            $makeRow('2816', 'C', 'Industrias manufactureras', 'Fabricación de equipo de elevación y manipulación'),
            $makeRow('2817', 'C', 'Industrias manufactureras', 'Fabricación de maquinaria y equipo de oficina (excepto computadoras y equipo periférico)'),
            $makeRow('2818', 'C', 'Industrias manufactureras', 'Fabricación de herramientas manuales con motor'),
            $makeRow('2819', 'C', 'Industrias manufactureras', 'Fabricación de otros tipos de maquinaria y equipo de uso general'),
            $makeRow('2821', 'C', 'Industrias manufactureras', 'Fabricación de maquinaria agropecuaria y forestal'),
            $makeRow('2822', 'C', 'Industrias manufactureras', 'Fabricación de máquinas formadoras de metal y de máquinas herramienta'),
            $makeRow('2823', 'C', 'Industrias manufactureras', 'Fabricación de maquinaria para la metalurgia'),
            $makeRow('2824', 'C', 'Industrias manufactureras', 'Fabricación de maquinaria para explotación de minas y canteras y para obras de construcción'),
            $makeRow('2825', 'C', 'Industrias manufactureras', 'Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco'),
            $makeRow('2826', 'C', 'Industrias manufactureras', 'Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros'),
            $makeRow('2829', 'C', 'Industrias manufactureras', 'Fabricación de otros tipos de maquinaria y equipo de uso especial'),
            $makeRow('2910', 'C', 'Industrias manufactureras', 'Fabricación de vehículos automotores y sus motores'),
            $makeRow('2920', 'C', 'Industrias manufactureras', 'Fabricación de carrocerías para vehículos automotores; remolques y semirremolques'),
            $makeRow('2930', 'C', 'Industrias manufactureras', 'Fabricación de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores'),
            $makeRow('3011', 'C', 'Industrias manufactureras', 'Construcción de barcos y de estructuras flotantes'),
            $makeRow('3012', 'C', 'Industrias manufactureras', 'Construcción de embarcaciones de recreo y de deporte'),
            $makeRow('3020', 'C', 'Industrias manufactureras', 'Fabricación de locomotoras y de material rodante para ferrocarriles'),
            $makeRow('3030', 'C', 'Industrias manufactureras', 'Fabricación de aeronaves, naves espaciales y de maquinaria conexa'),
            $makeRow('3040', 'C', 'Industrias manufactureras', 'Fabricación de vehículos militares de combate'),
            $makeRow('3091', 'C', 'Industrias manufactureras', 'Fabricación de motocicletas'),
            $makeRow('3092', 'C', 'Industrias manufactureras', 'Fabricación de bicicletas y de sillas de ruedas para personas con discapacidad'),
            $makeRow('3099', 'C', 'Industrias manufactureras', 'Fabricación de otros tipos de equipo de transporte no clasificados en otra parte'),
            $makeRow('3110', 'C', 'Industrias manufactureras', 'Fabricación de muebles'),
            $makeRow('3120', 'C', 'Industrias manufactureras', 'Fabricación de colchones y somieres'),
            $makeRow('3210', 'C', 'Industrias manufactureras', 'Fabricación de joyas, bisutería y artículos conexos'),
            $makeRow('3220', 'C', 'Industrias manufactureras', 'Fabricación de instrumentos musicales'),
            $makeRow('3230', 'C', 'Industrias manufactureras', 'Fabricación de artículos y equipo para la práctica del deporte y el atletismo'),
            $makeRow('3240', 'C', 'Industrias manufactureras', 'Fabricación de juegos, juguetes y rompecabezas'),
            $makeRow('3250', 'C', 'Industrias manufactureras', 'Fabricación de instrumentos, aparatos y materiales médicos y odontológicos (incluido mobiliario)'),
            $makeRow('3290', 'C', 'Industrias manufactureras', 'Otras industrias manufactureras no clasificadas en otra parte'),
            $makeRow('3311', 'C', 'Industrias manufactureras', 'Mantenimiento y reparación especializado de productos elaborados en metal'),
            $makeRow('3312', 'C', 'Industrias manufactureras', 'Mantenimiento y reparación especializado de maquinaria y equipo'),
            $makeRow('3313', 'C', 'Industrias manufactureras', 'Mantenimiento y reparación especializado de equipo electrónico y óptico'),
            $makeRow('3314', 'C', 'Industrias manufactureras', 'Mantenimiento y reparación especializado de equipo eléctrico'),
            $makeRow('3315', 'C', 'Industrias manufactureras', 'Mantenimiento y reparación especializado de equipo de transporte (excepto automotores y motocicletas)'),
            $makeRow('3316', 'C', 'Industrias manufactureras', 'Mantenimiento y reparación especializado de aeronaves y naves espaciales'),
            $makeRow('3317', 'C', 'Industrias manufactureras', 'Mantenimiento y reparación especializado de barcos'),
            $makeRow('3319', 'C', 'Industrias manufactureras', 'Mantenimiento y reparación de otros tipos de equipos y sus componentes'),
            $makeRow('3320', 'C', 'Industrias manufactureras', 'Instalación especializada de maquinaria y equipo industrial'),

            // =========================================================
            // SECCIÓN D: Suministro de electricidad, gas, vapor y aire acondicionado
            // =========================================================
            $makeRow('3511', 'D', 'Suministro de electricidad, gas, vapor y aire acondicionado', 'Generación de energía eléctrica'),
            $makeRow('3512', 'D', 'Suministro de electricidad, gas, vapor y aire acondicionado', 'Transmisión de energía eléctrica'),
            $makeRow('3513', 'D', 'Suministro de electricidad, gas, vapor y aire acondicionado', 'Distribución de energía eléctrica'),
            $makeRow('3514', 'D', 'Suministro de electricidad, gas, vapor y aire acondicionado', 'Comercialización de energía eléctrica'),
            $makeRow('3520', 'D', 'Suministro de electricidad, gas, vapor y aire acondicionado', 'Producción de gas; distribución de combustibles gaseosos por tuberías'),
            $makeRow('3530', 'D', 'Suministro de electricidad, gas, vapor y aire acondicionado', 'Suministro de vapor y de aire acondicionado'),

            // =========================================================
            // SECCIÓN E: Distribución de agua; evacuación y tratamiento de aguas residuales,
            //            gestión de desechos y actividades de saneamiento ambiental
            // =========================================================
            $makeRow('3600', 'E', 'Distribución de agua; evacuación y tratamiento de aguas residuales, gestión de desechos y saneamiento', 'Captación, tratamiento y distribución de agua'),
            $makeRow('3700', 'E', 'Distribución de agua; evacuación y tratamiento de aguas residuales, gestión de desechos y saneamiento', 'Evacuación y tratamiento de aguas residuales'),
            $makeRow('3811', 'E', 'Distribución de agua; evacuación y tratamiento de aguas residuales, gestión de desechos y saneamiento', 'Recolección de desechos no peligrosos'),
            $makeRow('3812', 'E', 'Distribución de agua; evacuación y tratamiento de aguas residuales, gestión de desechos y saneamiento', 'Recolección de desechos peligrosos'),
            $makeRow('3821', 'E', 'Distribución de agua; evacuación y tratamiento de aguas residuales, gestión de desechos y saneamiento', 'Tratamiento y disposición de desechos no peligrosos'),
            $makeRow('3822', 'E', 'Distribución de agua; evacuación y tratamiento de aguas residuales, gestión de desechos y saneamiento', 'Tratamiento y disposición de desechos peligrosos'),
            $makeRow('3830', 'E', 'Distribución de agua; evacuación y tratamiento de aguas residuales, gestión de desechos y saneamiento', 'Recuperación de materiales'),
            $makeRow('3900', 'E', 'Distribución de agua; evacuación y tratamiento de aguas residuales, gestión de desechos y saneamiento', 'Actividades de saneamiento ambiental y otros servicios de gestión de desechos'),

            // =========================================================
            // SECCIÓN F: Construcción
            // =========================================================
            $makeRow('4111', 'F', 'Construcción', 'Construcción de edificios residenciales'),
            $makeRow('4112', 'F', 'Construcción', 'Construcción de edificios no residenciales'),
            $makeRow('4210', 'F', 'Construcción', 'Construcción de carreteras y vías de ferrocarril'),
            $makeRow('4220', 'F', 'Construcción', 'Construcción de proyectos de servicio público'),
            $makeRow('4290', 'F', 'Construcción', 'Construcción de otras obras de ingeniería civil'),
            $makeRow('4311', 'F', 'Construcción', 'Demolición'),
            $makeRow('4312', 'F', 'Construcción', 'Preparación del terreno'),
            $makeRow('4321', 'F', 'Construcción', 'Instalaciones eléctricas'),
            $makeRow('4322', 'F', 'Construcción', 'Instalaciones de fontanería, calefacción y aire acondicionado'),
            $makeRow('4329', 'F', 'Construcción', 'Otras instalaciones especializadas'),
            $makeRow('4330', 'F', 'Construcción', 'Terminación y acabado de edificios y obras de ingeniería civil'),
            $makeRow('4390', 'F', 'Construcción', 'Otras actividades especializadas para la construcción de edificios y obras de ingeniería civil'),

            // =========================================================
            // SECCIÓN G: Comercio al por mayor y al por menor;
            //            reparación de vehículos automotores y motocicletas
            // =========================================================
            $makeRow('4511', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio de vehículos automotores nuevos'),
            $makeRow('4512', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio de vehículos automotores usados'),
            $makeRow('4520', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Mantenimiento y reparación de vehículos automotores'),
            $makeRow('4530', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores'),
            $makeRow('4541', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio de motocicletas y de sus partes, piezas y accesorios'),
            $makeRow('4542', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Mantenimiento y reparación de motocicletas y de sus partes y piezas'),
            $makeRow('4610', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por mayor a cambio de una retribución o por contrata'),
            $makeRow('4620', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por mayor de materias primas agropecuarias; animales vivos'),
            $makeRow('4631', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por mayor de productos alimenticios'),
            $makeRow('4632', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por mayor de bebidas y tabaco'),
            $makeRow('4641', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por mayor de productos textiles, productos confeccionados para uso doméstico'),
            $makeRow('4642', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por mayor de prendas de vestir'),
            $makeRow('4643', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por mayor de calzado'),
            $makeRow('4644', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por mayor de aparatos y equipo de uso doméstico'),
            $makeRow('4645', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por mayor de productos farmacéuticos, medicinales, cosméticos y de tocador'),
            $makeRow('4649', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por mayor de otros utensilios domésticos'),
            $makeRow('4651', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por mayor de computadoras, equipo periférico y programas de informática'),
            $makeRow('4652', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por mayor de equipo, partes y piezas electrónicos y de telecomunicaciones'),
            $makeRow('4653', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por mayor de maquinaria y equipo agropecuarios'),
            $makeRow('4659', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por mayor de otros tipos de maquinaria y equipo'),
            $makeRow('4661', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por mayor de combustibles sólidos, líquidos, gaseosos y productos conexos'),
            $makeRow('4662', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por mayor de metales y productos metalíferos'),
            $makeRow('4663', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por mayor de materiales de construcción, artículos de ferretería, pinturas y productos de vidrio'),
            $makeRow('4664', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por mayor de productos químicos básicos, cauchos y plásticos y productos de uso agropecuario'),
            $makeRow('4665', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por mayor de desperdicios, desechos y chatarra'),
            $makeRow('4669', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por mayor de otros productos no clasificados en otra parte'),
            $makeRow('4690', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por mayor no especializado'),
            $makeRow('4711', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por menor en establecimientos no especializados con surtido compuesto principalmente de alimentos, bebidas o tabaco'),
            $makeRow('4719', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por menor en establecimientos no especializados, con surtido compuesto principalmente por productos diferentes de alimentos, bebidas y tabaco'),
            $makeRow('4721', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por menor de productos agrícolas para el consumo en establecimientos especializados'),
            $makeRow('4722', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por menor de leche, productos lácteos y huevos en establecimientos especializados'),
            $makeRow('4723', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por menor de carne y productos cárnicos en establecimientos especializados'),
            $makeRow('4724', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por menor de bebidas y productos del tabaco en establecimientos especializados'),
            $makeRow('4725', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por menor de productos de panadería, pastelería y confitería en establecimientos especializados'),
            $makeRow('4729', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por menor de otros productos alimenticios no clasificados en otra parte, en establecimientos especializados'),
            $makeRow('4731', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por menor de combustible para automotores'),
            $makeRow('4732', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por menor de lubricantes (aceites, grasas), aditivos y productos de limpieza para automotores'),
            $makeRow('4741', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por menor de computadoras, equipos periféricos, programas de informática y equipos de telecomunicaciones en establecimientos especializados'),
            $makeRow('4742', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por menor de equipos y aparatos de sonido y de video en establecimientos especializados'),
            $makeRow('4751', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por menor de productos textiles en establecimientos especializados'),
            $makeRow('4752', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por menor de artículos de ferretería, pinturas y productos de vidrio en establecimientos especializados'),
            $makeRow('4753', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por menor de tapices, alfombras y cubrimientos para paredes y pisos en establecimientos especializados'),
            $makeRow('4754', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por menor de electrodomésticos y gasodomésticos, muebles y equipos de iluminación'),
            $makeRow('4755', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por menor de artículos y utensilios de uso doméstico'),
            $makeRow('4759', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por menor de otros artículos domésticos en establecimientos especializados'),
            $makeRow('4761', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por menor de libros, periódicos, materiales y artículos de papelería y escritorio en establecimientos especializados'),
            $makeRow('4762', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por menor de artículos deportivos en establecimientos especializados'),
            $makeRow('4763', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por menor de juegos, juguetes y artículos de entretenimiento en establecimientos especializados'),
            $makeRow('4771', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por menor de prendas de vestir y sus accesorios en establecimientos especializados'),
            $makeRow('4772', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por menor de todo tipo de calzado y artículos de cuero en establecimientos especializados'),
            $makeRow('4773', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por menor de productos farmacéuticos y medicinales, cosméticos y artículos de tocador en establecimientos especializados'),
            $makeRow('4774', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por menor de otros productos nuevos en establecimientos especializados'),
            $makeRow('4781', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por menor de alimentos, bebidas y tabaco, en puestos de venta móviles'),
            $makeRow('4782', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por menor de productos textiles, prendas de vestir y calzado, en puestos de venta móviles'),
            $makeRow('4789', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por menor de otros productos en puestos de venta móviles'),
            $makeRow('4791', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por menor realizado a través de internet'),
            $makeRow('4792', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Comercio al por menor realizado a través de casas de venta o por correo'),
            $makeRow('4799', 'G', 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas', 'Otros tipos de comercio al por menor no realizado en establecimientos, puestos de venta o mercados'),

            // =========================================================
            // SECCIÓN H: Transporte y almacenamiento
            // =========================================================
            $makeRow('4911', 'H', 'Transporte y almacenamiento', 'Transporte férreo de pasajeros'),
            $makeRow('4912', 'H', 'Transporte y almacenamiento', 'Transporte férreo de carga'),
            $makeRow('4921', 'H', 'Transporte y almacenamiento', 'Transporte de pasajeros'),
            $makeRow('4922', 'H', 'Transporte y almacenamiento', 'Transporte mixto'),
            $makeRow('4923', 'H', 'Transporte y almacenamiento', 'Transporte de carga por carretera'),
            $makeRow('4930', 'H', 'Transporte y almacenamiento', 'Transporte por tuberías'),
            $makeRow('5011', 'H', 'Transporte y almacenamiento', 'Transporte marítimo y de cabotaje de pasajeros'),
            $makeRow('5012', 'H', 'Transporte y almacenamiento', 'Transporte marítimo y de cabotaje de carga'),
            $makeRow('5021', 'H', 'Transporte y almacenamiento', 'Transporte fluvial de pasajeros'),
            $makeRow('5022', 'H', 'Transporte y almacenamiento', 'Transporte fluvial de carga'),
            $makeRow('5111', 'H', 'Transporte y almacenamiento', 'Transporte aéreo nacional de pasajeros'),
            $makeRow('5112', 'H', 'Transporte y almacenamiento', 'Transporte aéreo internacional de pasajeros'),
            $makeRow('5121', 'H', 'Transporte y almacenamiento', 'Transporte aéreo nacional de carga'),
            $makeRow('5122', 'H', 'Transporte y almacenamiento', 'Transporte aéreo internacional de carga'),
            $makeRow('5210', 'H', 'Transporte y almacenamiento', 'Almacenamiento y depósito'),
            $makeRow('5221', 'H', 'Transporte y almacenamiento', 'Actividades de servicios vinculadas al transporte terrestre'),
            $makeRow('5222', 'H', 'Transporte y almacenamiento', 'Actividades de servicios vinculadas al transporte acuático'),
            $makeRow('5223', 'H', 'Transporte y almacenamiento', 'Actividades de servicios vinculadas al transporte aéreo'),
            $makeRow('5224', 'H', 'Transporte y almacenamiento', 'Manipulación de carga'),
            $makeRow('5229', 'H', 'Transporte y almacenamiento', 'Otras actividades complementarias al transporte'),
            $makeRow('5310', 'H', 'Transporte y almacenamiento', 'Actividades postales nacionales'),
            $makeRow('5320', 'H', 'Transporte y almacenamiento', 'Actividades de mensajería'),

            // =========================================================
            // SECCIÓN I: Alojamiento y servicios de comida
            // =========================================================
            $makeRow('5511', 'I', 'Alojamiento y servicios de comida', 'Alojamiento en hoteles'),
            $makeRow('5512', 'I', 'Alojamiento y servicios de comida', 'Alojamiento en apartahoteles'),
            $makeRow('5513', 'I', 'Alojamiento y servicios de comida', 'Alojamiento en centros vacacionales'),
            $makeRow('5514', 'I', 'Alojamiento y servicios de comida', 'Alojamiento rural'),
            $makeRow('5519', 'I', 'Alojamiento y servicios de comida', 'Otros tipos de alojamiento para visitantes'),
            $makeRow('5520', 'I', 'Alojamiento y servicios de comida', 'Actividades de zonas de camping y parques para vehículos recreacionales'),
            $makeRow('5530', 'I', 'Alojamiento y servicios de comida', 'Servicio por horas'),
            $makeRow('5590', 'I', 'Alojamiento y servicios de comida', 'Otros tipos de alojamiento no clasificados en otra parte'),
            $makeRow('5611', 'I', 'Alojamiento y servicios de comida', 'Expendio a la mesa de comidas preparadas'),
            $makeRow('5612', 'I', 'Alojamiento y servicios de comida', 'Expendio por autoservicio de comidas preparadas'),
            $makeRow('5613', 'I', 'Alojamiento y servicios de comida', 'Expendio de comidas preparadas en cafeterías'),
            $makeRow('5619', 'I', 'Alojamiento y servicios de comida', 'Otros tipos de expendio de comidas preparadas'),
            $makeRow('5621', 'I', 'Alojamiento y servicios de comida', 'Catering para eventos'),
            $makeRow('5629', 'I', 'Alojamiento y servicios de comida', 'Actividades de otros servicios de comidas'),
            $makeRow('5630', 'I', 'Alojamiento y servicios de comida', 'Expendio de bebidas alcohólicas para el consumo dentro del establecimiento'),

            // =========================================================
            // SECCIÓN J: Información y comunicaciones
            // =========================================================
            $makeRow('5811', 'J', 'Información y comunicaciones', 'Edición de libros'),
            $makeRow('5812', 'J', 'Información y comunicaciones', 'Edición de directorios y listas de correo'),
            $makeRow('5813', 'J', 'Información y comunicaciones', 'Edición de periódicos, revistas y otras publicaciones periódicas'),
            $makeRow('5819', 'J', 'Información y comunicaciones', 'Otros trabajos de edición'),
            $makeRow('5820', 'J', 'Información y comunicaciones', 'Edición de programas de informática (software)'),
            $makeRow('5911', 'J', 'Información y comunicaciones', 'Actividades de producción de películas cinematográficas, videos, programas y comerciales de televisión'),
            $makeRow('5912', 'J', 'Información y comunicaciones', 'Actividades de posproducción de películas cinematográficas, videos y programas de televisión'),
            $makeRow('5913', 'J', 'Información y comunicaciones', 'Actividades de distribución de películas cinematográficas, videos y programas de televisión'),
            $makeRow('5914', 'J', 'Información y comunicaciones', 'Actividades de exhibición de películas cinematográficas y videos'),
            $makeRow('5920', 'J', 'Información y comunicaciones', 'Actividades de grabación de sonido y edición de música'),
            $makeRow('6010', 'J', 'Información y comunicaciones', 'Actividades de radiodifusión (radio)'),
            $makeRow('6020', 'J', 'Información y comunicaciones', 'Actividades de programación y transmisión de televisión'),
            $makeRow('6110', 'J', 'Información y comunicaciones', 'Actividades de telecomunicaciones alámbricas'),
            $makeRow('6120', 'J', 'Información y comunicaciones', 'Actividades de telecomunicaciones inalámbricas'),
            $makeRow('6130', 'J', 'Información y comunicaciones', 'Actividades de telecomunicación satelital'),
            $makeRow('6190', 'J', 'Información y comunicaciones', 'Otras actividades de telecomunicaciones'),
            $makeRow('6201', 'J', 'Información y comunicaciones', 'Actividades de desarrollo de sistemas informáticos (planificación, análisis, diseño, programación, pruebas)'),
            $makeRow('6202', 'J', 'Información y comunicaciones', 'Actividades de consultoría informática y administración de instalaciones informáticas'),
            $makeRow('6209', 'J', 'Información y comunicaciones', 'Otras actividades de tecnología de información y actividades de servicios informáticos'),
            $makeRow('6311', 'J', 'Información y comunicaciones', 'Procesamiento de datos, hospedaje (hosting) y actividades relacionadas'),
            $makeRow('6312', 'J', 'Información y comunicaciones', 'Portales web'),
            $makeRow('6391', 'J', 'Información y comunicaciones', 'Actividades de agencias de noticias'),
            $makeRow('6399', 'J', 'Información y comunicaciones', 'Otras actividades de servicios de información no clasificadas en otra parte'),

            // =========================================================
            // SECCIÓN K: Actividades financieras y de seguros
            // =========================================================
            $makeRow('6411', 'K', 'Actividades financieras y de seguros', 'Banco Central'),
            $makeRow('6412', 'K', 'Actividades financieras y de seguros', 'Bancos comerciales'),
            $makeRow('6421', 'K', 'Actividades financieras y de seguros', 'Corporaciones financieras'),
            $makeRow('6422', 'K', 'Actividades financieras y de seguros', 'Compañías de financiamiento'),
            $makeRow('6423', 'K', 'Actividades financieras y de seguros', 'Banca de segundo piso'),
            $makeRow('6424', 'K', 'Actividades financieras y de seguros', 'Cooperativas de ahorro y crédito'),
            $makeRow('6431', 'K', 'Actividades financieras y de seguros', 'Fondos de cesantías'),
            $makeRow('6432', 'K', 'Actividades financieras y de seguros', 'Fondos de pensiones y cesantías'),
            $makeRow('6433', 'K', 'Actividades financieras y de seguros', 'Pensiones de jubilación (patrimonios autónomos)'),
            $makeRow('6434', 'K', 'Actividades financieras y de seguros', 'Fondo nacional de pensiones de las entidades territoriales (FONPET)'),
            $makeRow('6435', 'K', 'Actividades financieras y de seguros', 'Entidades de carácter especial y entidades sin ánimo de lucro que captan ahorro'),
            $makeRow('6436', 'K', 'Actividades financieras y de seguros', 'Fondos de inversión colectiva'),
            $makeRow('6437', 'K', 'Actividades financieras y de seguros', 'Fondos comunes ordinarios y especiales administrados por sociedades fiduciarias'),
            $makeRow('6438', 'K', 'Actividades financieras y de seguros', 'Fiducias y otros vehículos de inversión colectiva administrados por sociedades fiduciarias'),
            $makeRow('6439', 'K', 'Actividades financieras y de seguros', 'Otras actividades de servicios financieros'),
            $makeRow('6441', 'K', 'Actividades financieras y de seguros', 'Leasing habitacional'),
            $makeRow('6442', 'K', 'Actividades financieras y de seguros', 'Leasing no habitacional'),
            $makeRow('6491', 'K', 'Actividades financieras y de seguros', 'Casas de cambio'),
            $makeRow('6492', 'K', 'Actividades financieras y de seguros', 'Capitalización'),
            $makeRow('6493', 'K', 'Actividades financieras y de seguros', 'Actividades financieras de Fogafin y Fogacoop'),
            $makeRow('6494', 'K', 'Actividades financieras y de seguros', 'Actividades de las sociedades de capitalización'),
            $makeRow('6495', 'K', 'Actividades financieras y de seguros', 'Financiación de planes de seguro de vida'),
            $makeRow('6496', 'K', 'Actividades financieras y de seguros', 'Casas de empeño y prestamistas sobre alhajas'),
            $makeRow('6499', 'K', 'Actividades financieras y de seguros', 'Otras actividades de servicio financiero no clasificadas en otra parte'),
            $makeRow('6511', 'K', 'Actividades financieras y de seguros', 'Seguros generales'),
            $makeRow('6512', 'K', 'Actividades financieras y de seguros', 'Seguros de vida'),
            $makeRow('6513', 'K', 'Actividades financieras y de seguros', 'Seguros sociales obligatorios'),
            $makeRow('6521', 'K', 'Actividades financieras y de seguros', 'Servicios de reaseguros'),
            $makeRow('6522', 'K', 'Actividades financieras y de seguros', 'Pensiones y cesantías de las empresas aseguradoras'),
            $makeRow('6523', 'K', 'Actividades financieras y de seguros', 'Servicios de seguros de riesgos laborales'),
            $makeRow('6531', 'K', 'Actividades financieras y de seguros', 'Administración de Fondos Pensionales'),
            $makeRow('6532', 'K', 'Actividades financieras y de seguros', 'Administración de Fondos de Cesantías'),
            $makeRow('6611', 'K', 'Actividades financieras y de seguros', 'Administración de mercados financieros'),
            $makeRow('6612', 'K', 'Actividades financieras y de seguros', 'Corretaje de valores y de contratos de productos básicos'),
            $makeRow('6613', 'K', 'Actividades financieras y de seguros', 'Otras actividades relacionadas con el mercado de valores'),
            $makeRow('6614', 'K', 'Actividades financieras y de seguros', 'Actividades de las casas de cambio'),
            $makeRow('6615', 'K', 'Actividades financieras y de seguros', 'Actividades de los profesionales de compra y venta de divisas'),
            $makeRow('6619', 'K', 'Actividades financieras y de seguros', 'Otras actividades auxiliares de las actividades de servicios financieros'),
            $makeRow('6621', 'K', 'Actividades financieras y de seguros', 'Actividades de agentes y corredores de seguros'),
            $makeRow('6629', 'K', 'Actividades financieras y de seguros', 'Evaluación de riesgos y daños, y otras actividades de servicios auxiliares'),
            $makeRow('6630', 'K', 'Actividades financieras y de seguros', 'Actividades de administración de fondos'),

            // =========================================================
            // SECCIÓN L: Actividades inmobiliarias
            // =========================================================
            $makeRow('6810', 'L', 'Actividades inmobiliarias', 'Actividades inmobiliarias realizadas con bienes propios o arrendados'),
            $makeRow('6820', 'L', 'Actividades inmobiliarias', 'Actividades inmobiliarias realizadas a cambio de una retribución o por contrata'),

            // =========================================================
            // SECCIÓN M: Actividades profesionales, científicas y técnicas
            // =========================================================
            $makeRow('6910', 'M', 'Actividades profesionales, científicas y técnicas', 'Actividades jurídicas'),
            $makeRow('6920', 'M', 'Actividades profesionales, científicas y técnicas', 'Actividades de contabilidad, teneduría de libros, auditoría financiera y asesoría tributaria'),
            $makeRow('7010', 'M', 'Actividades profesionales, científicas y técnicas', 'Actividades de administración empresarial'),
            $makeRow('7020', 'M', 'Actividades profesionales, científicas y técnicas', 'Actividades de consultores de gestión empresarial'),
            $makeRow('7110', 'M', 'Actividades profesionales, científicas y técnicas', 'Actividades de arquitectura e ingeniería y otras actividades conexas de consultoría técnica'),
            $makeRow('7120', 'M', 'Actividades profesionales, científicas y técnicas', 'Ensayos y análisis técnicos'),
            $makeRow('7210', 'M', 'Actividades profesionales, científicas y técnicas', 'Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería'),
            $makeRow('7220', 'M', 'Actividades profesionales, científicas y técnicas', 'Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades'),
            $makeRow('7310', 'M', 'Actividades profesionales, científicas y técnicas', 'Publicidad'),
            $makeRow('7320', 'M', 'Actividades profesionales, científicas y técnicas', 'Estudios de mercado y realización de encuestas de opinión pública'),
            $makeRow('7410', 'M', 'Actividades profesionales, científicas y técnicas', 'Actividades especializadas de diseño'),
            $makeRow('7420', 'M', 'Actividades profesionales, científicas y técnicas', 'Actividades de fotografía'),
            $makeRow('7490', 'M', 'Actividades profesionales, científicas y técnicas', 'Otras actividades profesionales, científicas y técnicas no clasificadas en otra parte'),
            $makeRow('7500', 'M', 'Actividades profesionales, científicas y técnicas', 'Actividades veterinarias'),

            // =========================================================
            // SECCIÓN N: Actividades de servicios administrativos y de apoyo
            // =========================================================
            $makeRow('7710', 'N', 'Actividades de servicios administrativos y de apoyo', 'Alquiler y arrendamiento de vehículos automotores'),
            $makeRow('7721', 'N', 'Actividades de servicios administrativos y de apoyo', 'Alquiler y arrendamiento de equipos recreativos y deportivos'),
            $makeRow('7722', 'N', 'Actividades de servicios administrativos y de apoyo', 'Alquiler de videos y discos de video digital (DVD)'),
            $makeRow('7723', 'N', 'Actividades de servicios administrativos y de apoyo', 'Alquiler y arrendamiento de otros efectos personales y enseres domésticos'),
            $makeRow('7730', 'N', 'Actividades de servicios administrativos y de apoyo', 'Alquiler y arrendamiento de otros tipos de maquinaria, equipo y bienes tangibles'),
            $makeRow('7740', 'N', 'Actividades de servicios administrativos y de apoyo', 'Arrendamiento de propiedad intelectual y productos similares, excepto obras protegidas por derechos de autor'),
            $makeRow('7810', 'N', 'Actividades de servicios administrativos y de apoyo', 'Actividades de empresas de servicios de empleo temporal'),
            $makeRow('7820', 'N', 'Actividades de servicios administrativos y de apoyo', 'Actividades de agencias de empleo'),
            $makeRow('7830', 'N', 'Actividades de servicios administrativos y de apoyo', 'Otras formas de suministro de recurso humano'),
            $makeRow('7911', 'N', 'Actividades de servicios administrativos y de apoyo', 'Actividades de las agencias de viaje'),
            $makeRow('7912', 'N', 'Actividades de servicios administrativos y de apoyo', 'Actividades de operadores turísticos'),
            $makeRow('7990', 'N', 'Actividades de servicios administrativos y de apoyo', 'Otros servicios de reserva y actividades relacionadas'),
            $makeRow('8010', 'N', 'Actividades de servicios administrativos y de apoyo', 'Actividades de seguridad privada'),
            $makeRow('8020', 'N', 'Actividades de servicios administrativos y de apoyo', 'Actividades de servicios de sistemas de seguridad'),
            $makeRow('8030', 'N', 'Actividades de servicios administrativos y de apoyo', 'Actividades de detectives e investigadores privados'),
            $makeRow('8110', 'N', 'Actividades de servicios administrativos y de apoyo', 'Actividades combinadas de apoyo a instalaciones'),
            $makeRow('8121', 'N', 'Actividades de servicios administrativos y de apoyo', 'Limpieza general interior de edificios'),
            $makeRow('8122', 'N', 'Actividades de servicios administrativos y de apoyo', 'Otras actividades de limpieza de edificios e instalaciones industriales'),
            $makeRow('8129', 'N', 'Actividades de servicios administrativos y de apoyo', 'Otras actividades de limpieza'),
            $makeRow('8130', 'N', 'Actividades de servicios administrativos y de apoyo', 'Actividades de paisajismo y servicios de mantenimiento conexos'),
            $makeRow('8210', 'N', 'Actividades de servicios administrativos y de apoyo', 'Actividades de oficinas administrativas y de apoyo'),
            $makeRow('8220', 'N', 'Actividades de servicios administrativos y de apoyo', 'Actividades de centros de llamadas (call center)'),
            $makeRow('8230', 'N', 'Actividades de servicios administrativos y de apoyo', 'Organización, manejo y realización de congresos, convenciones y eventos'),
            $makeRow('8291', 'N', 'Actividades de servicios administrativos y de apoyo', 'Actividades de agencias de cobro y oficinas de calificación crediticia'),
            $makeRow('8292', 'N', 'Actividades de servicios administrativos y de apoyo', 'Actividades de envasado y empaque'),
            $makeRow('8299', 'N', 'Actividades de servicios administrativos y de apoyo', 'Otras actividades de servicios de apoyo a las empresas no clasificadas en otra parte'),

            // =========================================================
            // SECCIÓN O: Administración pública y defensa; planes de seguridad social
            // =========================================================
            $makeRow('8411', 'O', 'Administración pública y defensa; planes de seguridad social de afiliación obligatoria', 'Actividades legislativas de la administración pública'),
            $makeRow('8412', 'O', 'Administración pública y defensa; planes de seguridad social de afiliación obligatoria', 'Actividades ejecutivas de la administración pública'),
            $makeRow('8413', 'O', 'Administración pública y defensa; planes de seguridad social de afiliación obligatoria', 'Regulación de las actividades de organismos que prestan servicios de salud, educativos, culturales y otros servicios sociales'),
            $makeRow('8414', 'O', 'Administración pública y defensa; planes de seguridad social de afiliación obligatoria', 'Actividades reguladoras y facilitadoras de la actividad económica'),
            $makeRow('8415', 'O', 'Administración pública y defensa; planes de seguridad social de afiliación obligatoria', 'Actividades de los demás órganos de control'),
            $makeRow('8421', 'O', 'Administración pública y defensa; planes de seguridad social de afiliación obligatoria', 'Relaciones exteriores'),
            $makeRow('8422', 'O', 'Administración pública y defensa; planes de seguridad social de afiliación obligatoria', 'Actividades de defensa'),
            $makeRow('8423', 'O', 'Administración pública y defensa; planes de seguridad social de afiliación obligatoria', 'Orden público y actividades de seguridad'),
            $makeRow('8424', 'O', 'Administración pública y defensa; planes de seguridad social de afiliación obligatoria', 'Administración de justicia'),
            $makeRow('8425', 'O', 'Administración pública y defensa; planes de seguridad social de afiliación obligatoria', 'Actividades de protección civil'),
            $makeRow('8430', 'O', 'Administración pública y defensa; planes de seguridad social de afiliación obligatoria', 'Actividades de planes de seguridad social de afiliación obligatoria'),

            // =========================================================
            // SECCIÓN P: Educación
            // =========================================================
            $makeRow('8511', 'P', 'Educación', 'Educación de la primera infancia'),
            $makeRow('8512', 'P', 'Educación', 'Educación preescolar'),
            $makeRow('8513', 'P', 'Educación', 'Educación básica primaria'),
            $makeRow('8521', 'P', 'Educación', 'Educación básica secundaria'),
            $makeRow('8522', 'P', 'Educación', 'Educación media académica'),
            $makeRow('8523', 'P', 'Educación', 'Educación media técnica y de formación laboral'),
            $makeRow('8530', 'P', 'Educación', 'Establecimientos que combinan diferentes niveles de educación'),
            $makeRow('8541', 'P', 'Educación', 'Educación técnica profesional'),
            $makeRow('8542', 'P', 'Educación', 'Educación tecnológica'),
            $makeRow('8543', 'P', 'Educación', 'Educación de instituciones universitarias o de escuelas tecnológicas'),
            $makeRow('8544', 'P', 'Educación', 'Educación de universidades'),
            $makeRow('8551', 'P', 'Educación', 'Formación para el trabajo'),
            $makeRow('8552', 'P', 'Educación', 'Educación cultural y artística'),
            $makeRow('8553', 'P', 'Educación', 'Educación deportiva y recreacional'),
            $makeRow('8559', 'P', 'Educación', 'Otros tipos de educación no clasificados en otra parte'),
            $makeRow('8560', 'P', 'Educación', 'Actividades de apoyo a la educación'),

            // =========================================================
            // SECCIÓN Q: Actividades de atención de la salud humana y de asistencia social
            // =========================================================
            $makeRow('8610', 'Q', 'Actividades de atención de la salud humana y de asistencia social', 'Actividades de hospitales y clínicas, con internación'),
            $makeRow('8621', 'Q', 'Actividades de atención de la salud humana y de asistencia social', 'Actividades de la práctica médica, sin internación'),
            $makeRow('8622', 'Q', 'Actividades de atención de la salud humana y de asistencia social', 'Actividades de la práctica odontológica'),
            $makeRow('8691', 'Q', 'Actividades de atención de la salud humana y de asistencia social', 'Actividades de apoyo diagnóstico'),
            $makeRow('8692', 'Q', 'Actividades de atención de la salud humana y de asistencia social', 'Actividades de apoyo terapéutico'),
            $makeRow('8699', 'Q', 'Actividades de atención de la salud humana y de asistencia social', 'Otras actividades de atención de la salud humana'),
            $makeRow('8710', 'Q', 'Actividades de atención de la salud humana y de asistencia social', 'Actividades de atención residencial medicalizada de enfermedades mentales y consumo de sustancias psicoactivas'),
            $makeRow('8720', 'Q', 'Actividades de atención de la salud humana y de asistencia social', 'Actividades de atención residencial para personas con retraso mental, enfermedad mental y consumo de sustancias psicoactivas'),
            $makeRow('8730', 'Q', 'Actividades de atención de la salud humana y de asistencia social', 'Actividades de atención en instituciones para el cuidado de personas mayores y/o discapacitadas'),
            $makeRow('8790', 'Q', 'Actividades de atención de la salud humana y de asistencia social', 'Otras actividades de atención en instituciones con alojamiento'),
            $makeRow('8810', 'Q', 'Actividades de atención de la salud humana y de asistencia social', 'Actividades de asistencia social sin alojamiento para personas adultas y discapacitadas'),
            $makeRow('8890', 'Q', 'Actividades de atención de la salud humana y de asistencia social', 'Otras actividades de asistencia social sin alojamiento'),

            // =========================================================
            // SECCIÓN R: Actividades artísticas, de entretenimiento y recreación
            // =========================================================
            $makeRow('9001', 'R', 'Actividades artísticas, de entretenimiento y recreación', 'Creación literaria'),
            $makeRow('9002', 'R', 'Actividades artísticas, de entretenimiento y recreación', 'Creación musical'),
            $makeRow('9003', 'R', 'Actividades artísticas, de entretenimiento y recreación', 'Creación teatral'),
            $makeRow('9004', 'R', 'Actividades artísticas, de entretenimiento y recreación', 'Creación audiovisual'),
            $makeRow('9005', 'R', 'Actividades artísticas, de entretenimiento y recreación', 'Artes plásticas y visuales'),
            $makeRow('9006', 'R', 'Actividades artísticas, de entretenimiento y recreación', 'Actividades teatrales'),
            $makeRow('9007', 'R', 'Actividades artísticas, de entretenimiento y recreación', 'Actividades de espectáculos musicales en vivo'),
            $makeRow('9008', 'R', 'Actividades artísticas, de entretenimiento y recreación', 'Otras actividades de espectáculos en vivo'),
            $makeRow('9101', 'R', 'Actividades artísticas, de entretenimiento y recreación', 'Actividades de bibliotecas y archivos'),
            $makeRow('9102', 'R', 'Actividades artísticas, de entretenimiento y recreación', 'Actividades y funcionamiento de museos, conservación de edificios y sitios históricos'),
            $makeRow('9103', 'R', 'Actividades artísticas, de entretenimiento y recreación', 'Actividades de jardines botánicos, zoológicos y reservas naturales'),
            $makeRow('9200', 'R', 'Actividades artísticas, de entretenimiento y recreación', 'Actividades de juegos de azar y apuestas'),
            $makeRow('9311', 'R', 'Actividades artísticas, de entretenimiento y recreación', 'Gestión de instalaciones deportivas'),
            $makeRow('9312', 'R', 'Actividades artísticas, de entretenimiento y recreación', 'Actividades de clubes deportivos'),
            $makeRow('9319', 'R', 'Actividades artísticas, de entretenimiento y recreación', 'Otras actividades deportivas'),
            $makeRow('9321', 'R', 'Actividades artísticas, de entretenimiento y recreación', 'Actividades de parques de atracciones y parques temáticos'),
            $makeRow('9329', 'R', 'Actividades artísticas, de entretenimiento y recreación', 'Otras actividades recreativas y de esparcimiento no clasificadas en otra parte'),

            // =========================================================
            // SECCIÓN S: Otras actividades de servicios
            // =========================================================
            $makeRow('9411', 'S', 'Otras actividades de servicios', 'Actividades de asociaciones empresariales y de empleadores'),
            $makeRow('9412', 'S', 'Otras actividades de servicios', 'Actividades de asociaciones profesionales'),
            $makeRow('9420', 'S', 'Otras actividades de servicios', 'Actividades de sindicatos de empleados'),
            $makeRow('9491', 'S', 'Otras actividades de servicios', 'Actividades de asociaciones religiosas'),
            $makeRow('9492', 'S', 'Otras actividades de servicios', 'Actividades de asociaciones políticas'),
            $makeRow('9499', 'S', 'Otras actividades de servicios', 'Actividades de otras asociaciones no clasificadas en otra parte'),
            $makeRow('9511', 'S', 'Otras actividades de servicios', 'Mantenimiento y reparación de computadoras y de equipo periférico'),
            $makeRow('9512', 'S', 'Otras actividades de servicios', 'Mantenimiento y reparación de equipos de comunicación'),
            $makeRow('9521', 'S', 'Otras actividades de servicios', 'Mantenimiento y reparación de aparatos electrónicos de consumo'),
            $makeRow('9522', 'S', 'Otras actividades de servicios', 'Mantenimiento y reparación de aparatos y equipos domésticos y de jardinería'),
            $makeRow('9523', 'S', 'Otras actividades de servicios', 'Reparación de calzado y artículos de cuero'),
            $makeRow('9524', 'S', 'Otras actividades de servicios', 'Reparación de muebles y accesorios para el hogar'),
            $makeRow('9529', 'S', 'Otras actividades de servicios', 'Mantenimiento y reparación de otros efectos personales y enseres domésticos'),
            $makeRow('9601', 'S', 'Otras actividades de servicios', 'Lavado y limpieza, incluso la limpieza en seco, de productos textiles y de piel'),
            $makeRow('9602', 'S', 'Otras actividades de servicios', 'Peluquería y otros tratamientos de belleza'),
            $makeRow('9603', 'S', 'Otras actividades de servicios', 'Pompas fúnebres y actividades relacionadas'),
            $makeRow('9609', 'S', 'Otras actividades de servicios', 'Otras actividades de servicios personales no clasificadas en otra parte'),

            // =========================================================
            // SECCIÓN T: Actividades de los hogares individuales
            // =========================================================
            $makeRow('9700', 'T', 'Actividades de los hogares individuales en calidad de empleadores', 'Actividades de los hogares individuales como empleadores de personal doméstico'),
            $makeRow('9810', 'T', 'Actividades de los hogares individuales en calidad de empleadores', 'Actividades no diferenciadas de los hogares individuales como productores de bienes para uso propio'),
            $makeRow('9820', 'T', 'Actividades de los hogares individuales en calidad de empleadores', 'Actividades no diferenciadas de los hogares individuales como productores de servicios para uso propio'),

            // =========================================================
            // SECCIÓN U: Actividades de organizaciones y entidades extraterritoriales
            // =========================================================
            $makeRow('9900', 'U', 'Actividades de organizaciones y entidades extraterritoriales', 'Actividades de organizaciones y entidades extraterritoriales'),
        ];
    }
}
