bs = chr(92)
sq = chr(39)
ds = chr(36)
lines = []
lines.append("<?php")
lines.append("")
lines.append("namespace App\Filament\Admin\Resources\ReglamentoInternoResource\Pages;")
lines.append("")
lines.append("use App\Filament\Admin\Resources\ReglamentoInternoResource;")
lines.append("use App\Models\ActividadEconomica;")
lines.append("use App\Models\Empresa;")
lines.append("use App\Models\ReglamentoInterno;")
lines.append("use App\Services\RITGeneratorService;")
lines.append("use Filament\Forms;")
lines.append("use Filament\Forms\Components\Wizard\Step;")
lines.append("use Filament\Forms\Get;")
lines.append("use Filament\Notifications\Notification;")
lines.append("use Filament\Resources\Pages\CreateRecord;")
lines.append("use Filament\Resources\Pages\CreateRecord\Concerns\HasWizard;")
lines.append("use Illuminate\Database\Eloquent\Model;")
lines.append("use Illuminate\Support\Facades\Auth;")
lines.append("use Illuminate\Support\Facades\Log;")
lines.append("use Illuminate\Support\HtmlString;")
print(chr(10).join(lines[:5]))